### PR TITLE
Increase Test Coverage for monolithic-layered app

### LINKED ISSUE #11: Increase Test Coverage for monolithic-layered app
The [monolithic/monolithic-layered](https://github.com/aabarmin/epam-microservices-training-2022/tree/main/monolithic/monolithic-layered) module currently has 0% test coverage. While performing manual testing, I encountered a few bugs. This issue aims to address the lack of automated tests for this module and ensure better reliability.

1. Write unit tests for individual components:

    - Services
    - Controllers
    - Repositories

2. Write integration tests to cover end-to-end flows of the app.

Please provide a PR with added tests, any bug fixes, and a brief description of the changes. Address any bugs or discrepancies found during testing. Any found bugs should be documented, and if they are outside the scope of this issue, separate issues should be opened.

### Benefits

- Better code reliability.
- Reduced chances of regression.
- Faster detection of issues in the future.

### PR DESCRIPTION
**Pull request by naXa777**
This pull request significantly enhances the unit and integration test coverage across controllers, services, and repositories of the monolithic-layered app.

### Demo

tests in maven

test coverage

### Related Issues

Closes #11

### CODE REVIEW

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    @Disabled("FIXME https://github.com/aabarmin/epam-microservices-training-2022/issues/28")
+    @Test
+    @DisplayName("Test viewSingle for non-existent Disease")
+    public void shouldReturnNotFoundForNonExistentDisease() throws Exception {
+        MockHttpServletRequestBuilder viewSingleReq = get("/diseases/404404");
+        this.mockMvc.perform(viewSingleReq)
+                .andExpect(status().isNotFound());
+    }
```
Comment (naXa777) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java:62]: I've marked tests with `@Disabled` annotations for known issues, providing a clear indication of items that need future attention.

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DrugControllerIT.java [hunk 2]
```diff
@@ -0,0 +1,68 @@
...
+
+    @Test
+    @DisplayName("Test viewAll endpoint")
+    public void shouldReturnAllDrugsList() throws Exception {
+        MockHttpServletRequestBuilder viewAllReq = get("/drugs");
+        this.mockMvc.perform(viewAllReq)
+                .andExpect(status().isOk())
+                // TODO uncomment after fix of #8
+                // .andExpect(content().string(containsString("<title>The Drug System - Drugs</title>")))
+                .andExpect(content().string(containsString(">Drugs</h1>")))
```
Comment (naXa777) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DrugControllerIT.java]: Note: commented out some assertions for known issues.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/web/DiseaseController.java [hunk 3]
```diff
@@ -30,7 +30,7 @@ public ViewAllTemplateParams getViewAllTemplateParams() {
   @Override
   public ViewSingleTemplateParams getViewSingleTemplateParams() {
     return ViewSingleTemplateParams.builder()
-        .title("Edit disease")
+        .title("Edit Disease")
```
Comment (naXa777) [inline monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/web/DiseaseController.java:33]: I've discovered a cosmetic issue thanks to tests and fixed it immediately.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java [hunk 4]
```diff
@@ -24,6 +25,7 @@ public class Pharmacy {
   private String name;
   private String address;
 
+  @ToString.Exclude
   @OneToMany(mappedBy = "pharmacy", cascade = CascadeType.ALL)
   private Set<PharmacyAvailable> available = Sets.newHashSet();
```
Comment (naXa777) [inline monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java]: Another issue discovered thanks to tests: `StackOverflowError` in `toString()` method (generated by lombok) due to cyclic dependencies between `Pharmacy` and `PharmacyAvailable` entities.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/delivery/Delivery.java [hunk 5]
```diff
@@ -49,8 +50,9 @@ public class Delivery {
     private Pharmacy pharmacy;
 
     /**
-     * Content of the com.epam.training.service.delivery.
+     * Content of the delivery.
      */
+    @ToString.Exclude
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/delivery/Delivery.java]: I think, the `pharmacy` field should also be exclude from `toString` as it is already excluded from equals and hashCode. Would it be better to put `@ToString(exclude={“pharmacy”, “content”})` on top of the class?

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java (hunk 4 above)
Comment (aabarmin) [reply monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java]: Just for consistency, would it be better to fix the issue by adding `@ToString` annotation to the class? The reason to do that is to have all the lombok annotations in one place and fields are annotated with JPA annotations only.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/recipie/Recipe.java [hunk 6]
```diff
@@ -29,17 +30,18 @@ public class Recipe {
...
-     * A recipient of the recipie. 
+     * A recipient of the recipie.
      */
     @ManyToOne(fetch = FetchType.EAGER)
     private Recipient recipient;
 
     /**
-     * A content of the recipie. 
+     * A content of the recipie.
      */
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/recipie/Recipe.java:44]: Here the same as in the previous class.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/recipie/Recipient.java [hunk 7]
```diff
@@ -23,14 +24,15 @@ public class Recipient {
...
      */
-    private String firstName; 
-    private String lastName; 
+    private String firstName;
+    private String lastName;
 
     /**
      * A collection of recipes associated with this recipient.
      */
+    @ToString.Exclude
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/recipie/Recipient.java]: The same suggestion as for the previous class if it is ok for you.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/web/DiseaseController.java (hunk 3 above)
Comment (aabarmin) [reply monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/web/DiseaseController.java:33]: Sure!

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/DataJpaTest.java [hunk 8]
```diff
@@ -0,0 +1,12 @@
+package com.epam.training.microservices.monolithic.service;
+
+import org.springframework.beans.factory.annotation.Autowired;
+import org.springframework.boot.test.autoconfigure.orm.jpa.TestEntityManager;
+
+@org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/DataJpaTest.java]: Assume, it is better to use import and put just `@DataJpaTest` on the class itself and rename the class to something like `BaseDataJpaTest` or `AbstractDataJpaTest` in order not to confuse own classes with well-known Spring’s classes.

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/delivery/DeliveryServiceTest.java [hunk 9]
```diff
@@ -0,0 +1,78 @@
...
+
+    @DisplayName("Test save method")
+    @Test
+    void shouldSaveDelivery() {
+        Delivery delivery = new Delivery();
+        when(deliveryRepository.save(delivery)).thenReturn(delivery);
+
+        Delivery savedDelivery = deliveryService.save(delivery);
+
+        assertEquals(delivery, savedDelivery);
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/delivery/DeliveryServiceTest.java:51]: Another good think to check is that the method was actually called, and here Mockito’s `verify` is an outstanding fit. Something like this: 

```java
verify(deliveryRepository, times(1)).save(eq(delivery));
```

This is a useful thing to add.

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/doctor/RecipeRepositoryTest.java [hunk 10]
```diff
@@ -0,0 +1,52 @@
...
+    @Autowired
+    private DoctorRepository doctorRepository;
+
+    @Autowired
+    private RecipientRepository recipientRepository;
+
+    @Test
+    public void shouldSaveAndRetrieveRecipe() {
+        // Arrange
+        Doctor doctor = new Doctor();
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/doctor/RecipeRepositoryTest.java]: Btw, if you don’t want to create complex entities, it is always possible to use `Doctor doctor = mock(Doctor.class)` or use a third-party library like EasyRandom. It is useful for scenarios when the data itself is not important and can be random.

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java [hunk 11]
```diff
@@ -0,0 +1,65 @@
...
+    @Test
+    @DisplayName("Test viewSingle endpoint for Diseases")
+    public void shouldReturnSpecificDiseaseDetails() throws Exception {
+        MockHttpServletRequestBuilder viewSingleReq = get("/diseases/1");
+        this.mockMvc.perform(viewSingleReq)
+                .andExpect(status().isOk())
+                // TODO uncomment after fix of #8
+                // .andExpect(content().string(containsString("<title>The Drug System - Edit Disease</title>")))
+                .andExpect(content().string(containsString(">Edit Disease</h1>")))
+                .andExpect(content().string(containsString("Asperger syndrome")))
```
Comment (aabarmin) [inline monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java:39]: HTMLUnit is a great option for assertions like this because it allows to check that the element is not only present in the HTML but also it is placed in the right place.

**Review by aabarmin — CHANGES_REQUESTED** [review]
Looks really good, thank you @naXa777 for contributing. Please let me know if you have any questions regarding my suggestions.

File: monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java (hunk 4 above)
Comment (naXa777) [reply monolithic/monolithic-layered/src/main/java/com/epam/training/microservices/monolithic/model/pharmacy/Pharmacy.java]: ok

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/doctor/RecipeRepositoryTest.java (hunk 10 above)
Comment (naXa777) [reply monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/doctor/RecipeRepositoryTest.java]: I keep this in mind. But in these tests and with these simple entities there's no big difference.

Comment (aabarmin) [reply monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/service/doctor/RecipeRepositoryTest.java]: Sure

File: monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java (hunk 11 above)
Comment (naXa777) [reply monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java:39]: I don't know how to integrate HTMLUnit with Spring MockMVC. I don't want to start a real web server, because I think it will make tests slower.

1. The official integration between Spring MVC Test and HTMLUnit is outdated. See https://mvnrepository.com/artifact/org.springframework.test.htmlunit/spring-test-htmlunit which was last updated May 14, 2015.
2. When I tried to simply use `final HtmlPage page = webClient.getPage("http://localhost/diseases")` as written in the [official documentation](https://www.htmlunit.org/gettingStarted.html), I got error "org.htmlunit.FailingHttpStatusCodeException: 404 Not Found for http://localhost/diseases".

There's nobody to respond to requests sent by HTMLUnit web client. Because I'm using [MockMVC](https://docs.spring.io/spring-framework/reference/testing/spring-mvc-test-framework.html) in tests:

> It performs full Spring MVC request handling but via mock request and response objects instead of a running server.

Comment (aabarmin) [reply monolithic/monolithic-layered/src/test/java/com/epam/training/microservices/monolithic/web/DiseaseControllerIT.java:39]: Sure, leave it to me, when have time I'll add integration with it.

**Review by aabarmin — APPROVED** [review]
Looks good to me, thank you for contributing
